name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update file
        run: echo "$(date)" >> daily.txt

      - name: Commit changes
        run: |
          git config --global user.name "Karthick Bot"
          git config --global user.email "irakkarthi@ksriet.ac.in"
          git add daily.txt
          git commit -m "🤖 Daily commit: $(date)" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

