name: Random Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:      # Allows you to run it manually

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make random change
        run: |
          echo "$(date)" >> daily.txt

      - name: Commit changes
        run: |
          git config --global user.name "Karthick Bot"
          git config --global user.email "irakkarthi@ksriet.ac.in"
          git add daily.txt
          git commit -m "🤖 Daily update: $(date)" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
